In [58]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path("..")
DATA_DIR = BASE_DIR / "data" / "raw"

df_2023 = pd.read_csv(DATA_DIR / "acidentes2023_todas_causas.csv", sep=";", encoding="latin1")
df_2024 = pd.read_csv(DATA_DIR / "acidentes2024_todas_causas.csv", sep=";", encoding="latin1")
df_2025 = pd.read_csv(DATA_DIR / "acidentes2025_todas_causas.csv", sep=";", encoding="latin1")

In [59]:
import pandas as pd

df_2023 = pd.read_csv(
    "../data/raw/acidentes2023_todas_causas.csv",
    sep=";",
    encoding="latin1"
)

df_2024 = pd.read_csv(
    "../data/raw/acidentes2024_todas_causas.csv",
    sep=";",
    encoding="latin1"
)

df_2025 = pd.read_csv(
    "../data/raw/acidentes2025_todas_causas.csv",
    sep=";",
    encoding="latin1"
)

In [60]:
#Data

for df in [df_2023, df_2024, df_2025]:
    df["data_inversa"] = pd.to_datetime(
        df["data_inversa"],
        errors="coerce"
    )

In [61]:
#KM
for df in [df_2023, df_2024, df_2025]:
    df["km"] = pd.to_numeric(
        df["km"],
        errors="coerce"
    )

In [62]:
#Longitude

for df in [df_2023, df_2024, df_2025]:
    if "longitude" in df.columns:
        df["longitude"] = pd.to_numeric(
            df["longitude"],
            errors="coerce"
        )

In [63]:
#latitude

for df in [df_2023, df_2025]:
    if "latitude" in df.columns:
        df["latitude"] = pd.to_numeric(
            df["latitude"],
            errors="coerce"
        )

In [64]:
#pesid

for df in [df_2023, df_2024, df_2025]:
    if "pesid" in df.columns:
        df["pesid"] = pd.to_numeric(
            df["pesid"],
            errors="coerce"
        ).astype("Int64")

In [65]:
#id_veiculos

for df in [df_2023, df_2024, df_2025]:
    if "id_veiculo" in df.columns:
        df["id_veiculo"] = pd.to_numeric(
            df["id_veiculo"],
            errors="coerce"
        ).astype("Int64")

In [66]:
#ano_fabricacao_veiculo

for df in [df_2023, df_2024, df_2025]:
    if "ano_fabricacao_veiculo" in df.columns:
        df["ano_fabricacao_veiculo"] = pd.to_numeric(
            df["ano_fabricacao_veiculo"],
            errors="coerce"
        ).astype("Int64")

In [67]:
#Alterando colunas de nulos para não informado


colunas_categoricas = [ #definindo as colunas categóricas para preencher os nulos com "Não informado"
    "classificacao_acidente",
    "regional",
    "delegacia",
    "uop",
    "tipo_veiculo",
    "tipo_envolvido",
    "condicao_metereologica"
]

for df in [df_2023, df_2024, df_2025]: # aplicando o tratamento nos 3 anos 
    for col in colunas_categoricas: # percorrendo as variáveis categoria
        if col in df.columns: #verificando possiveis erro nos anos caso exista dados diferentes
            df[col] = df[col].fillna("Não informado")

In [68]:
# data_inversa / uf

for df in [df_2023, df_2024, df_2025]:
    df.dropna(subset=["data_inversa", "uf"], inplace=True)

In [69]:
#conferindo os dataframes tratados

df_2023.shape, df_2024.shape, df_2025.shape

((571052, 37), (603215, 37), (528380, 37))

In [70]:
#criando tabela de ano

df_2023["ano"] = 2023
df_2024["ano"] = 2024
df_2025["ano"] = 2025

In [71]:
#conferindo tabela de ano

print("2023:", df_2023["ano"].unique())
print("2024:", df_2024["ano"].unique())
print("2025:", df_2025["ano"].unique())

2023: [2023]
2024: [2024]
2025: [2025]

In [72]:
#unindo os anos 

df_final = pd.concat(
    [df_2023, df_2024, df_2025],
    ignore_index=True
)

In [73]:
#visualizando df_final

df_final.shape

(1702647, 38)

In [74]:
#conferindo a coluna de ano

df_final["ano"].value_counts().sort_index()

ano
2023    571052
2024    603215
2025    528380
Name: count, dtype: int64

In [75]:
df_final

,id,pesid,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_principal,...,ilesos,feridos_leves,feridos_graves,mortos,latitude,longitude,regional,delegacia,uop,ano
0,496506.0,1082142,2023-01-01,domingo,00:15:00,MG,116.0,587.0,MANHUACU,Não,...,0.0,1.0,0.0,0.0,NaN,NaN,SPRF-MG,DEL06-MG,UOP03-DEL06-MG,2023
1,496506.0,1082142,2023-01-01,domingo,00:15:00,MG,116.0,587.0,MANHUACU,Sim,...,0.0,1.0,0.0,0.0,NaN,NaN,SPRF-MG,DEL06-MG,UOP03-DEL06-MG,2023
2,496506.0,1082142,2023-01-01,domingo,00:15:00,MG,116.0,587.0,MANHUACU,Não,...,0.0,1.0,0.0,0.0,NaN,NaN,SPRF-MG,DEL06-MG,UOP03-DEL06-MG,2023
3,496506.0,1082142,2023-01-01,domingo,00:15:00,MG,116.0,587.0,MANHUACU,Sim,...,0.0,1.0,0.0,0.0,NaN,NaN,SPRF-MG,DEL06-MG,UOP03-DEL06-MG,2023
4,496507.0,1082138,2023-01-01,domingo,00:20:00,MG,381.0,NaN,LAVRAS,Sim,...,0.0,1.0,0.0,0.0,NaN,NaN,SPRF-MG,DEL04-MG,UOP02-DEL04-MG,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1702642,740231.0,1656441,2025-11-12,quarta-feira,07:17:00,SC,280.0,NaN,GUARAMIRIM,Sim,...,0.0,1.0,0.0,0.0,NaN,NaN,SPRF-SC,DEL03-SC,UOP03-DEL03-SC,2025
1702643,740243.0,1656354,2025-11-29,sábado,08:42:00,RJ,101.0,496.0,ANGRA DOS REIS,Sim,...,1.0,0.0,0.0,0.0,NaN,NaN,SPRF-RJ,DEL03-RJ,UOP03-DEL03-RJ,2025
1702644,740243.0,1656353,2025-11-29,sábado,08:42:00,RJ,101.0,496.0,ANGRA DOS REIS,Sim,...,1.0,0.0,0.0,0.0,NaN,NaN,SPRF-RJ,DEL03-RJ,UOP03-DEL03-RJ,2025
1702645,740243.0,1656352,2025-11-29,sábado,08:42:00,RJ,101.0,496.0,ANGRA DOS REIS,Sim,...,0.0,1.0,0.0,0.0,NaN,NaN,SPRF-RJ,DEL03-RJ,UOP03-DEL03-RJ,2025
1702646,740243.0,1656351,2025-11-29,sábado,08:42:00,RJ,101.0,496.0,ANGRA DOS REIS,Sim,...,1.0,0.0,0.0,0.0,NaN,NaN,SPRF-RJ,DEL03-RJ,UOP03-DEL03-RJ,2025

In [76]:
#mudando o nome da coluna pesid para id_pessoa

df_final.rename(columns={"pesid": "id_pessoa"}, inplace=True)

In [77]:
#mudando o nome das colunas feridos para acidentes

df_final.rename(columns={"feridos_leves": "Acidentes_leves"}, inplace=True)
df_final.rename(columns={"feridos_graves": "Acidentes_graves"}, inplace=True)

In [78]:
#mudando o nome da coluna uop para código
df_final.rename(columns={"uop": "Código"}, inplace=True)

In [79]:
df_final

,id,id_pessoa,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_principal,...,ilesos,Acidentes_leves,Acidentes_graves,mortos,latitude,longitude,regional,delegacia,Código,ano
0,496506.0,1082142,2023-01-01,domingo,00:15:00,MG,116.0,587.0,MANHUACU,Não,...,0.0,1.0,0.0,0.0,NaN,NaN,SPRF-MG,DEL06-MG,UOP03-DEL06-MG,2023
1,496506.0,1082142,2023-01-01,domingo,00:15:00,MG,116.0,587.0,MANHUACU,Sim,...,0.0,1.0,0.0,0.0,NaN,NaN,SPRF-MG,DEL06-MG,UOP03-DEL06-MG,2023
2,496506.0,1082142,2023-01-01,domingo,00:15:00,MG,116.0,587.0,MANHUACU,Não,...,0.0,1.0,0.0,0.0,NaN,NaN,SPRF-MG,DEL06-MG,UOP03-DEL06-MG,2023
3,496506.0,1082142,2023-01-01,domingo,00:15:00,MG,116.0,587.0,MANHUACU,Sim,...,0.0,1.0,0.0,0.0,NaN,NaN,SPRF-MG,DEL06-MG,UOP03-DEL06-MG,2023
4,496507.0,1082138,2023-01-01,domingo,00:20:00,MG,381.0,NaN,LAVRAS,Sim,...,0.0,1.0,0.0,0.0,NaN,NaN,SPRF-MG,DEL04-MG,UOP02-DEL04-MG,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1702642,740231.0,1656441,2025-11-12,quarta-feira,07:17:00,SC,280.0,NaN,GUARAMIRIM,Sim,...,0.0,1.0,0.0,0.0,NaN,NaN,SPRF-SC,DEL03-SC,UOP03-DEL03-SC,2025
1702643,740243.0,1656354,2025-11-29,sábado,08:42:00,RJ,101.0,496.0,ANGRA DOS REIS,Sim,...,1.0,0.0,0.0,0.0,NaN,NaN,SPRF-RJ,DEL03-RJ,UOP03-DEL03-RJ,2025
1702644,740243.0,1656353,2025-11-29,sábado,08:42:00,RJ,101.0,496.0,ANGRA DOS REIS,Sim,...,1.0,0.0,0.0,0.0,NaN,NaN,SPRF-RJ,DEL03-RJ,UOP03-DEL03-RJ,2025
1702645,740243.0,1656352,2025-11-29,sábado,08:42:00,RJ,101.0,496.0,ANGRA DOS REIS,Sim,...,0.0,1.0,0.0,0.0,NaN,NaN,SPRF-RJ,DEL03-RJ,UOP03-DEL03-RJ,2025
1702646,740243.0,1656351,2025-11-29,sábado,08:42:00,RJ,101.0,496.0,ANGRA DOS REIS,Sim,...,1.0,0.0,0.0,0.0,NaN,NaN,SPRF-RJ,DEL03-RJ,UOP03-DEL03-RJ,2025

In [80]:
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 1702647 entries, 0 to 1702646
Data columns (total 38 columns):
 #   Column                  Dtype
---  ------                  -----
 0   id                      float64
 1   id_pessoa               Int64
 2   data_inversa            datetime64[us]
 3   dia_semana              str
 4   horario                 str
 5   uf                      str
 6   br                      float64
 7   km                      float64
 8   municipio               str
 9   causa_principal         str
 10  causa_acidente          str
 11  ordem_tipo_acidente     int64
 12  tipo_acidente           str
 13  classificacao_acidente  str
 14  fase_dia                str
 15  sentido_via             str
 16  condicao_metereologica  str
 17  tipo_pista              str
 18  tracado_via             str
 19  uso_solo                str
 20  id_veiculo              Int64
 21  tipo_veiculo            str
 22  marca                   str
 23  ano_fabricacao_veiculo  Int64
 24  tipo_envolvido          str
 25  estado_fisico           str
 26  idade                   float64
 27  sexo                    str
 28  ilesos                  float64
 29  Acidentes_leves         float64
 30  Acidentes_graves        float64
 31  mortos                  float64
 32  latitude                float64
 33  longitude               float64
 34  regional                str
 35  delegacia               str
 36  Código                  str
 37  ano                     int64
dtypes: Int64(3), datetime64[us](1), float64(10), int64(2), str(22)
memory usage: 498.5 MB

In [81]:
#analisando as colunas tratadas com dados alterados, verifiquei que a coluna id está como float e não inteiro, então farei a alteração para Int64 novamente.

df_final["id"] = (
    pd.to_numeric(df_final["id"], errors="coerce")
    .astype("Int64")
)

In [82]:
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 1702647 entries, 0 to 1702646
Data columns (total 38 columns):
 #   Column                  Dtype
---  ------                  -----
 0   id                      Int64
 1   id_pessoa               Int64
 2   data_inversa            datetime64[us]
 3   dia_semana              str
 4   horario                 str
 5   uf                      str
 6   br                      float64
 7   km                      float64
 8   municipio               str
 9   causa_principal         str
 10  causa_acidente          str
 11  ordem_tipo_acidente     int64
 12  tipo_acidente           str
 13  classificacao_acidente  str
 14  fase_dia                str
 15  sentido_via             str
 16  condicao_metereologica  str
 17  tipo_pista              str
 18  tracado_via             str
 19  uso_solo                str
 20  id_veiculo              Int64
 21  tipo_veiculo            str
 22  marca                   str
 23  ano_fabricacao_veiculo  Int64
 24  tipo_envolvido          str
 25  estado_fisico           str
 26  idade                   float64
 27  sexo                    str
 28  ilesos                  float64
 29  Acidentes_leves         float64
 30  Acidentes_graves        float64
 31  mortos                  float64
 32  latitude                float64
 33  longitude               float64
 34  regional                str
 35  delegacia               str
 36  Código                  str
 37  ano                     int64
dtypes: Int64(4), datetime64[us](1), float64(9), int64(2), str(22)
memory usage: 500.1 MB

In [83]:
df_final[["latitude", "longitude"]].dtypes

latitude     float64
longitude    float64
dtype: object

In [84]:
#Fazendo uma analise descritiva para verificar os dados tratados, verificando a média, mediana, min e max das colunas numéricas.
#count → quantidade de valores válidos
#mean → média
#std → desvio padrão
#min → menor valor
#25% → primeiro quartil
#50% → mediana
#75% → terceiro quartil
#max → maior valor

df_final["mortos"].describe()

count    1.536654e+06
mean     5.310760e-02
std      2.242481e-01
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      1.000000e+00
Name: mortos, dtype: float64

Analise do resultado:
1,5 milhão de acidentes
Em média 5,3 dos acidentes tem 1 morto
0,22 é binário, coerente.
Importante, 75% dos acidentes não são graves, pode existir desbalanceamento.
Máximo é 1 indica variável binária, ótimo.

Conclusão analítica: Os dados tem variável binária, sem valores estranhos, sem erro estrutural, pode conter desbalanceamento.

In [85]:
#Medindo o desbalanceamento

df_final["Acidentes_graves"].value_counts(normalize=True)

Acidentes_graves
0.0    0.872631
1.0    0.127369
Name: proportion, dtype: float64

87% dos acidentes não tem feridos graves
13% dos acidentes tem feridos graves

Analise, a cada 8 acidentes nas rodovias, 1 é acidente grave.

In [86]:
#salvando o dataframe tratado para o power bi

#from pathlib import Path

#processed_dir = Path("..") / "data" / "processed"
#processed_dir.mkdir(exist_ok=True)

#df_final.to_csv(
    #processed_dir / "acidentes_tratados_bi.csv",
    #index=False,
    #encoding="utf-8-sig"
#)